spring:
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:h2:mem:fitnessplanner
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 978db7001@smtp-brevo.com
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cron:
  expression: "0 37 15 ? * MON"
server:
  port: 8080

